version: '3'
services:
  uniswap-interface:
    build: .
    ports:
      - "3007:3000"
    environment:
      - NODE_ENV=development
      - REACT_APP_CHAIN_ID=23451
      - REACT_APP_NETWORK_URL=https://rpc.dreyerx.com
    stdin_open: true # Pastikan stdin tetap terbuka
    tty: true        # Pastikan tty tetap aktif
